### ISSUE TITLE
question: datapath and filename

### ISSUE THREAD

**Issue by MinjiLee-ku** [DeepBCI/Deep-BCI#1]
Hi,
I'm checking on SSVEP code and confirming that the 'datapath' and 'filename' in SSVEP_CCA_Classification and SSVEP_FFT_Visualization are different.
I think this part should be revised.

Thank you.

**Comment by ChaebinSong-ku** [comment]
Hello,

I checked SSVEP_CCA and FFT part as you said. There was an error in the path and filename of the SSVEP_CCA_Classification.

Thank you for your comment.
