### ISSUE TITLE
Where can I find the funcition named eegfile_loadBV?

### ISSUE THREAD

**Issue by youngseokkweon** [DeepBCI/Deep-BCI#16]
Where can I find a function called eegfile_loadBV in the file that exists in the link below?

https://github.com/DeepBCI/Deep-BCI/tree/master/2_1_Ambulatory_BCI
/Motor_imagery_on_treadmill/

**Comment by GihwanShin-ku** [comment]
The eegfile_loadBV function is in the bbci toolbox.

https://github.com/bbci/bbci_public
