### ISSUE TITLE
No code about Inter-subject Contrastive Learning for SubjectAdaptive EEG-based Visual Recognition

### ISSUE THREAD

**Issue by SirWlt** [DeepBCI/Deep-BCI#9]
Why have I not seen the code of this paper: _Inter-subject Contrastive Learning for SubjectAdaptive EEG-based Visual Recognition_?If it is convenient, could you please upload it again?

**Comment by Pilhyeon** [comment]
Thanks for your interest in our work and sorry for the inconvenience.
I have uploaded the code, which can be found [here](https://github.com/DeepBCI/Deep-BCI/tree/master/1_Intelligent_BCI/Inter_Subject_Contrastive_Learning_for_EEG).
If you have any further questions, please contact me via e-mail (lph1114@yonsei.ac.kr).
